### ISSUE TITLE
Save changes button doesnt seem to be lighting up

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2307]
Though it still functions.

This is on the latest master, not release.

1. Make a settings change

2. See results

**Comment by andytuba** [comment]
works okay for me, when switching a toggle or leaving a textbox after typing in it. maybe something else I just merged from @erikdesjardins fixed it?

**Comment by allthefoxes** [comment]
Still happening, just seems to be very specific.

https://www.allthefoxes.me/Bug2.webm

**Comment by allthefoxes** [comment]
Another example: Turning off inline images dims the page, **including the save button** (lol)

https://www.allthefoxes.me/Bug3.webm

**Comment by erikdesjardins** [comment]
This is intended behavior, toggling a module on/off is saved immediately (it's not stored with the options).

It made more sense when the save button was in the module, not the header, though, so this should be made more obvious (or it should be staged like options changes are).

**Comment by allthefoxes** [comment]
Yeah, I didn't realize this, and not realizing it, it looks like the extension is broken

**Comment by andytuba** [comment]
9fb205c95f248fa1635cd09f17622b1cc99220e8
