### ISSUE TITLE
Twitch Embed API changed - Twitch no longer works

### ISSUE THREAD

**Issue by molster** [honestbleeps/Reddit-Enhancement-Suite#5231]
Twitch  has updated their embed api, now required a new tag &parent= which must equal the site and the sub domain.. EG &parent=www.reddit.com   

However, this would need to support current path, in case people are on old.reddit.com ..etc

**Comment by BenMcGarry** [comment]
Fixed in 5232

**Comment by jmuravsky** [comment]
is this fix out in the official chrome release? because my embeds are still not working properly.
